# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-08-20 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[(b'Merchant', b'Merchant'), (b'Customer', b'Customer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[(b'Starter', b'Starter'), (b'Beverage', b'Beverage'), (b'Cold Beverage', b'Cold Beverage'), (b'Snack', b'Snack'), (b'Main Course', b'Main Course'), (b'Dessert', b'Dessert'), (b'Side', b'Side')], max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'store')]),
        ),
    ]
