# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-08-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_auto_20240817_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
