# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-08-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Beverage', 'Beverage'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert')], max_length=50),
        ),
    ]
